worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 5207;
        server_name _;
        
        # Allow large file uploads
        client_max_body_size 500M;

        # Forward real client IP and host
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Force https for Cloudflare tunnel to fix redirect issues
        proxy_set_header X-Forwarded-Proto "https";
        proxy_set_header X-Forwarded-Host $http_host;

        # Proxy to Next.js
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 600s;
            proxy_send_timeout 600s;
        }
    }
}
